apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: godfs-auth
  namespace: godfs
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: godfs-secretstore
    kind: SecretStore
  target:
    name: godfs-auth
    creationPolicy: Owner
  data:
    - secretKey: GODFS_CLUSTER_KEY
      remoteRef:
        key: godfs/cluster_key
    - secretKey: GODFS_API_KEYS
      remoteRef:
        key: godfs/api_keys
    - secretKey: GODFS_RBAC_JSON
      remoteRef:
        key: godfs/rbac_json
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: godfs-tls
  namespace: godfs
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: godfs-secretstore
    kind: SecretStore
  target:
    name: godfs-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: godfs/tls_crt
    - secretKey: tls.key
      remoteRef:
        key: godfs/tls_key
    - secretKey: ca.crt
      remoteRef:
        key: godfs/ca_crt

