# https://golangci-lint.run/docs/configuration/file/
version: "2"

run:
  timeout: 8m
  tests: true

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
  exclusions:
    rules:
      - path: '^api/proto/'
        linters:
          - staticcheck
          - unused
