apiVersion: v1
kind: Service
metadata:
  name: godfs-master-hs
  namespace: godfs
  labels:
    app.kubernetes.io/name: godfs-master
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: godfs-master
  ports:
    - name: grpc
      port: 9090
      targetPort: grpc
    - name: raft
      port: 9200
      targetPort: raft
    - name: metrics
      port: 9091
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: godfs-master
  namespace: godfs
  labels:
    app.kubernetes.io/name: godfs-master
spec:
  selector:
    app.kubernetes.io/name: godfs-master
  ports:
    - name: grpc
      port: 9090
      targetPort: grpc
    - name: metrics
      port: 9091
      targetPort: metrics

