apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-master-hs
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "godfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
spec:
  clusterIP: None
  selector:
    {{- include "godfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
  ports:
    - name: grpc
      port: {{ .Values.master.grpcPort }}
      targetPort: grpc
    - name: raft
      port: {{ .Values.master.raftPort }}
      targetPort: raft
    - name: metrics
      port: 9091
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-master
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "godfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
spec:
  selector:
    {{- include "godfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
  ports:
    - name: grpc
      port: {{ .Values.master.grpcPort }}
      targetPort: grpc
    - name: metrics
      port: 9091
      targetPort: metrics

