{{- if and .Values.prometheus.operator.enabled .Values.prometheus.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-master
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "godfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      {{- include "godfs.labels" . | nindent 6 }}
      app.kubernetes.io/component: master
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-chunk
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "godfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: chunk
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      {{- include "godfs.labels" . | nindent 6 }}
      app.kubernetes.io/component: chunk
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-restgateway
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "godfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: restgateway
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      {{- include "godfs.labels" . | nindent 6 }}
      app.kubernetes.io/component: restgateway
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
{{- end }}
