FROM golang:1.26-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/godfs-restgateway ./cmd/restgateway

FROM alpine:3.20
COPY --from=build /out/godfs-restgateway /usr/local/bin/
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/godfs-restgateway"]
