apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: godfs-chunk-data
  namespace: godfs
  labels:
    app.kubernetes.io/name: godfs-chunk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
