apiVersion: apps/v1
kind: Deployment
metadata:
  name: godfs-restgateway
  namespace: godfs
spec:
  replicas: 2
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: godfs-restgateway
                topologyKey: kubernetes.io/hostname
      containers:
        - name: restgateway
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /v1/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 4
